# SQLite. Versions 3.8.0 and up are supported.
# gem install sqlite3
#
# Ensure the SQLite 3 gem is defined in your Gemfile
# gem "sqlite3"

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %> # Change this if you want to use a static username
  password: <%= ENV['DATABASE_PASSWORD'] %> # Change this if you want to use a static password
  host: <%= ENV['PROD_DATABASE_HOST'] %>
  port: 5432

development:
  <<: *default
  database: budget_tracker_app_development

test:
  <<: *default
  database: budget_tracker_app_test

production:
  <<: *default
  database: budget_inu_db
  username: <%= ENV['PROD_DATABASE_USERNAME'] %>
  password: <%= ENV['PROD_DATABASE_PASSWORD'] %> 
